### ISSUE TITLE
The "search" feature of concourse-ci.org needs some love (e.g. zero results for "pinning")

### ISSUE THREAD

**Issue by marco-m** [concourse/docs#181]
Concourse 5 replaced "resource pausing" with "resource pinning". This is a fundamental aspect of Concourse, but searching for "pin" or "pinning" in the search bar on the top right of the website gives 0 results, although actually there is some text in the release notes in the https://concourse-ci.org/download.html page.

Not finding "pinning" is just an example; I remember other cases where I was looking for a Concourse concept in the search bar and had to fall back to various google search incantations to find it.

This is unfortunate because this means that also if the documentation of a feature/concept exists, it is actually invisible to somebody who doesn't already know it well.

**Comment by vito** [comment]
search was pretty broken and couldn't find simple results like 'vault', which is now fixed via https://github.com/concourse/docs/commit/64b707d0ddde9ad402a0ebaa259a2430eb97f844

however the specific things mentioned in this issue are not fixed by fixing search - that's more the fault of the documentation being literally nonexistant for pinning at the moment. release notes shouldn't really count as docs, and they aren't on the site anymore - we now put the release notes directly in the github releases.

maybe the next step would be to extend the search to also search content, not just titles? (and make sure that doesn't get in the way)

**Comment by marco-m** [comment]
Ah, I see. Yes, search should extend to content also. While we are talking about titles, the search has this (in my opinion counter-productive) characteristics of searching for single letters if a title has multiple words, generating wrong hits. I have to fall back to searching google with `site: concourse-ci.org` in the hope to find something :-(

**Comment by vito** [comment]
@marco-m Do you have an example of that with the new search functionality?

**Comment by vito** [comment]
Ok, I think this is all addressed by the above commit. :slightly_smiling_face: I special-cased single-letter word searches so they now require an exact match, and it'll now fall back on searching content if the title doesn't match. Content matches are also suggested after title matches so they don't get in the way of more likely searches.

**Comment by marco-m** [comment]
Thanks a lot vito! :-)
The exact match works, but I am not sure about the 

> it'll now fall back on searching content if the title doesn't match. 

For example, the content contains the word "metal" (https://concourse-ci.org/generic-oauth.html), but if I search for metal, I get 0 hits. Or am I misunderstanding ?

**Comment by vito** [comment]
@marco-m Woops, hadn't pushed it yet. Should work once the GitHub deploy propagates:

![Screenshot 2019-04-30 at 7 42 07 PM](https://user-images.githubusercontent.com/1880/57000082-155e5380-6b80-11e9-84b4-d7fc047a3b80.png)

**Comment by marco-m** [comment]
@vito thanks! This is a great improvement! ❤️
