### ISSUE TITLE
Architecture diagram showing tcp/2222 routing to TSA

### ISSUE THREAD

**Issue by rikkuness** [concourse/docs#265]
The diagram on the [architecture page](https://concourse-ci.org/architecture.html) shows inbound tcp/2222 through the loadbalancer going into the TSA, but from reading other areas of the documentation I understood that tcp/2222 was exposed by the ATC and not the TSA, is that correct?

Thanks

**Comment by pivotal-jamie-klassen** [comment]
with default settings, it's the [TSA](https://github.com/concourse/concourse/blob/master/tsa/tsacmd/command.go#L27) that listens on port 2222. Where did you see docs suggesting it was the ATC? For the most part, I think we should probably have our docs talking about the 'web node' since the ATC and TSA are internal details that operators probably shouldn't have to deal with. In fact, if you can identify the spot where we're saying the wrong thing, you could PR the fix to concourse/docs.

Unless there's a deeper followup here (like mistakes in our documentation or a related bug or feature request) 'help' questions like this are usually best directed to the [forum](https://discuss.concourse-ci.org) or [Discord](https://discord.gg/MeRxXKWz).

**Comment by rikkuness** [comment]
No worries, it could just be confusion in terms

**Comment by rikkuness** [comment]
Also your Discord link seems to be expired 😄sorry

**Comment by vito** [comment]
@rikkuness :thinking: What does it do for you? It still shows up and says 'expires: (infinity)' for me:

![Screenshot from 2019-10-21 10-03-03](https://user-images.githubusercontent.com/1880/67212201-ff707380-f3e9-11e9-908c-bec0e44cda41.png)

**Comment by pivotal-jamie-klassen** [comment]
it was my bad copypasta
