### ISSUE TITLE
I liked the older UI more

### ISSUE THREAD

**Issue by maryamklabib** [concourse/docs#39]
The previous UI for the site was extremely easy to search and pleasing to the eye. 

Please consider incorporating it back.

**Comment by AnianZ** [comment]
I have to say I was also a little bit confused seeing the new site in contrast to the old one. I get the motivation to create an experience more focused on information and developers but I also liked the more branded design with more visualisation of the old site.

And that would be my point of actionable feedback: The new page seems to have fewer visualisations than the old one. The link to concourses own pipeline on the start page for example is gone. And I also miss the prominent description of the concepts and architecture of concourse at the beginning of the docs. They are mentioned in the first sentence of the page but the links go direct to the docs for how to use them. I liked the more abstract description at the start of the old page.

Also I can't seem to find the visualisation of the different parts of concourse like the TSA, Baggagclaim and the communication between worker nodes and web nodes, all the different port etc. That graphic representation helped me a lot in understanding how I can set up and manage my concourse instance.

And a final note on the more basic appearance in general: As I said, I get where you are coming form and especially the search is really helpful. But I would not underestimate the value of a good design to attract new people to the project. Of course you don't want to sell a product but you want to "sell" it to interested developers and probably new contributors. The modern design with a nice logo, a clearly stated vision and also good documentation attracted me to the project. The current site looks more like its "just" documentation and not as much interested in attracting new people. Even if the content states otherwise.

**Comment by maryamklabib** [comment]
Hey everyone,

I wanted to take a step back and recognize the incredible work you all have put in the design of your website, your pipelines, your yaml, your discord, stack overflow, slack channels, etc.

I wanted to convey a feeling and didn't know where to. The context was that I was in a coding session with other devs and we wanted to reference the docs. We hadn't seen the new site and we expressed unanimous "first impressions" that we missed how pretty it used to be. I made this issue on the spot with the intent that it was a group of voices in a sea of many more, so please do take it with a grain of salt. 

I can't reference the older site right now but a lot of what @AnianZ pointed out above resonates with me. I liked having a physically large search functionality (like literally the search box is now smaller). I liked the branding and the aerospace metaphors. I liked seeing more sample manifest snippets. It feels like it's harder to find manifest dos and donts. You've all made some excellent points about how purposeful this recent design is, and you've thought about it longer than I have.

**Comment by jhamon** [comment]
I have really enjoyed the new search functionality but am slightly put off by the non-standard monospace font. When I first loaded this page with the new styles I actually went into my browser developer console tools to see if the fonts had loaded properly because I thought maybe I was seeing some kind of weird system font as a fallback. Perhaps it will grow on me but for now my reaction to `Iosevka`'s tall-and-narrow aesthetic is that it is definitely harder for me to read than `Source Code Pro`, `Inconsolata`, `Menlo`, `Monaco`, or really any other commonly used monospace font.

**Comment by vito** [comment]
@jhamon I hear ya. We've received similar feedback in the past. We'll take a look at others, or possibly try some tweaks to Iosevka (i.e. character spacing) that we've done before and received positive feedback.

I'm gonna close this issue before it turns into a grab-bag of feedback with a bunch of parallel discussions that all can't really be "closed". We should be using the [Site Feedback](https://discuss.concourse-ci.org/c/site-feedback) forum for this instead.

Thanks everyone!

**Comment by AnianZ** [comment]
Thanks for your detailed response @vito . These are some very valid points about sustainability and contributions you brought up there. Great that you are communicating that so open.

I won't bother this thread with more discussion and look to the forum instead :wink: I don't have a lot of time at the moment but maybe I can invest some to get a little deeper into concourse and the the docs and help out somewhere in the next month.
